Popis/Controllers/SredstvoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Popis.Data;
using Popis.Models;


namespace Popis.Controllers
{
    public class SredstvoesController : Controller
    {
        

        private  ApplicationDbContext _context { get; }

        public SredstvoesController(ApplicationDbContext context)
        {
           this._context = context;
        }

       

        // GET: Sredstvoes
        public async Task<IActionResult> Index()
        {
           
            var applicationDbContext = _context.Sredstvo.Include(s => s.Korisnik).Include(s => s.Lokacija);
            return View(await applicationDbContext.ToListAsync());
        }

        [HttpPost]
        public IActionResult Export()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[7] { new DataColumn("id"),
                                        new DataColumn("Naziv"),
                                        new DataColumn("Opis"),
                                        new DataColumn("DatumNabavke"),
                                        new DataColumn("DatumIsteka") ,
                                        new DataColumn("KorisnikId"),
                                        new DataColumn("LokacijaId") });

            var sredstvoes = from sredstvo in this._context.Sredstvo.Take(10)
                            select sredstvo;

            foreach (var sredstvo in sredstvoes)
            {
                dt.Rows.Add(sredstvo.id, sredstvo.Naziv,sredstvo.Opis, sredstvo.DatumNabavke, sredstvo.DatumIsteka,sredstvo.KorisnikId,sredstvo.LokacijaId);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Grid.xlsx");
                }
            }
        }


        // GET: Sredstvoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sredstvo = await _context.Sredstvo
                .Include(s => s.Korisnik)
                .Include(s => s.Lokacija)
                .FirstOrDefaultAsync(m => m.id == id);
            if (sredstvo == null)
            {
                return NotFound();
            }

            return View(sredstvo);
        }

        // GET: Sredstvoes/Create
        public IActionResult Create()
        {

            
            ViewData["KorisnikId"] = new SelectList(_context.Korisnik, "id", "Naziv");
            ViewData["LokacijaId"] = new SelectList(_context.Lokacija, "id", "Naziv");
            return View();
        }

        // POST: Sredstvoes/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Naziv,Opis,DatumNabavke,DatumIsteka,KorisnikId,LokacijaId")] Sredstvo sredstvo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sredstvo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["KorisnikId"] = new SelectList(_context.Korisnik, "id", "Naziv", sredstvo.KorisnikId);
            ViewData["LokacijaId"] = new SelectList(_context.Lokacija, "id", "Naziv", sredstvo.LokacijaId);
            return View(sredstvo);
        }

        // GET: Sredstvoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sredstvo = await _context.Sredstvo.FindAsync(id);
            if (sredstvo == null)
            {
                return NotFound();
            }
            ViewData["KorisnikId"] = new SelectList(_context.Korisnik, "id", "Naziv", sredstvo.KorisnikId);
            ViewData["LokacijaId"] = new SelectList(_context.Lokacija, "id", "Naziv", sredstvo.LokacijaId);
            return View(sredstvo);
        }

        // POST: Sredstvoes/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Naziv,Opis,DatumNabavke,DatumIsteka,KorisnikId,LokacijaId")] Sredstvo sredstvo)
        {
            if (id != sredstvo.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sredstvo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SredstvoExists(sredstvo.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KorisnikId"] = new SelectList(_context.Korisnik, "id", "Naziv", sredstvo.KorisnikId);
            ViewData["LokacijaId"] = new SelectList(_context.Lokacija, "id", "Naziv", sredstvo.LokacijaId);
            return View(sredstvo);
        }

        // GET: Sredstvoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sredstvo = await _context.Sredstvo
                .Include(s => s.Korisnik)
                .Include(s => s.Lokacija)
                .FirstOrDefaultAsync(m => m.id == id);
            if (sredstvo == null)
            {
                return NotFound();
            }

            return View(sredstvo);
        }

        // POST: Sredstvoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sredstvo = await _context.Sredstvo.FindAsync(id);
            _context.Sredstvo.Remove(sredstvo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SredstvoExists(int id)
        {
            return _context.Sredstvo.Any(e => e.id == id);
        }

    }
}

Popis/Views/Sredstvoes/Create.cshtml
@model Popis.Models.Sredstvo

@{
    ViewData["Title"] = "Create";
}

<h1>Kreiranje</h1>

<h6>Sredstvo</h6>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumNabavke" class="control-label"></label>
                <input asp-for="DatumNabavke" class="form-control" />
                <span asp-validation-for="DatumNabavke" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumIsteka" class="control-label"></label>
                <input asp-for="DatumIsteka" class="form-control" />
                <span asp-validation-for="DatumIsteka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KorisnikId" class="control-label"></label>
                <select asp-for="KorisnikId" class ="form-control" asp-items="ViewBag.KorisnikId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LokacijaId" class="control-label"></label>
                <select asp-for="LokacijaId" class ="form-control" asp-items="ViewBag.LokacijaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Nazad</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Popis/Views/Sredstvoes/Delete.cshtml
@model Popis.Models.Sredstvo

@{
    ViewData["Title"] = "Delete";
}

<h1>Obrisi</h1>

h6>Da li ste sigurni da zelite da obrisete sredstvo?</h6>
<div>
    <h4>Sredstvo</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatumNabavke)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatumNabavke)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatumIsteka)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatumIsteka)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Korisnik)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Lokacija)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Lokacija.Naziv)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Obrisi" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary">Nazad</a>
    </form>
</div>

Popis/Views/Sredstvoes/Details.cshtml
@model Popis.Models.Sredstvo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalji</h1>

<div>
    <h6>Sredstvo</h6>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumNabavke)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumNabavke)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumIsteka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumIsteka)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Korisnik)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lokacija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lokacija.Naziv)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id" class="btn btn-primary">Izmeni</a> |
    <a asp-action="Index" class="btn btn-primary">Nazad</a>
</div>

Popis/Views/Sredstvoes/Edit.cshtml
@model Popis.Models.Sredstvo

@{
    ViewData["Title"] = "Edit";
}

<h1>Izmeni</h1>

<h6>Sredstvo</h6>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumNabavke" class="control-label"></label>
                <input asp-for="DatumNabavke" class="form-control" />
                <span asp-validation-for="DatumNabavke" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumIsteka" class="control-label"></label>
                <input asp-for="DatumIsteka" class="form-control" />
                <span asp-validation-for="DatumIsteka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KorisnikId" class="control-label"></label>
                <select asp-for="KorisnikId" class="form-control" asp-items="ViewBag.KorisnikId"></select>
                <span asp-validation-for="KorisnikId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LokacijaId" class="control-label"></label>
                <select asp-for="LokacijaId" class="form-control" asp-items="ViewBag.LokacijaId"></select>
                <span asp-validation-for="LokacijaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sacuvaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Nazad</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Popis/Views/Sredstvoes/Index.cshtml
@model IEnumerable<Popis.Models.Sredstvo>

@{
    ViewData["Title"] = "Index";
}



<h1>Lista svih sredstava</h1>

<p>
    <a asp-controller="Sredstvoes" asp-action="Create" class="btn btn-primary">
        <i class="fas fa-plus"></i> &nbsp; Kreiraj novo sredstvo
    </a>
</p>

<form method="post" asp-controller="Sredstvoes" asp-action="Export">
    <input type="submit" value="Izvezi u Excel" class="btn btn-info" />
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumNabavke)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumIsteka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Korisnik)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lokacija)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Opis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumNabavke)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumIsteka)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Korisnik.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lokacija.Naziv)
                </td>
                <td>
                    <a asp-controller="Sredstvoes" asp-route-id="@item.id" asp-action="Edit" class="btn btn-primary">
                        <i class="fas fa-edit"></i> Izmeni
                    </a>
                    <a asp-controller="Sredstvoes" asp-action="Details" asp-route-id="@item.id" class="btn"><i class="fas fa-th-list"></i>Detalji</a>
                    <a asp-controller="Sredstvoes" asp-route-id="@item.id" asp-action="Delete" class="btn btn-danger">
                        <i class="fas fa-trash-alt"></i>  Obrisi
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>